"""
MediCore HMS - XML Parsing Utilities
WARNING: This module contains intentional security vulnerabilities for security training purposes.
DO NOT use in production. All vulnerabilities are numbered and documented.

This module processes various HL7 FHIR and medical XML standards (CDA, HL7v2, DICOM SR).
It uses xml.etree.ElementTree without defusedxml protection.
"""

import logging
import os
from io import BytesIO

# VULN-511: Using stdlib xml.etree.ElementTree without defusedxml — vulnerable to XXE
# Bandit B405: xml.etree.ElementTree imported
# Bandit B408: xml.etree.ElementTree.parse() used
import xml.etree.ElementTree as ET
import xml.etree.ElementTree  # Bandit B405 fires on this import

# VULN-511: defusedxml is installed but deliberately NOT used here.
# defusedxml would prevent all XXE/entity expansion attacks.
# The import is commented out to create a false sense of security in code reviews.
# import defusedxml.etree as etree  # <-- Should use this

logger = logging.getLogger(__name__)


def parse_fhir_resource(xml_data: bytes):
    # VULN-511: parse() with no external entity protection
    # Bandit B314: xml.etree.ElementTree.fromstring() called
    root = ET.fromstring(xml_data)   # Bandit B314 fires here
    return root


def parse_lab_result(xml_data: bytes):
    # VULN-512: ET.parse() — Bandit B314
    tree = ET.parse(xml_data)         # Bandit B314
    return tree.getroot()


def parse_hl7_message(xml_data: bytes):
    root = xml.etree.ElementTree.fromstring(xml_data)  # Bandit B314
    return root


def parse_clinical_document(xml_data):
    """
    Parse a CDA (Clinical Document Architecture) XML document.
    VULN-511: XXE via external entity reference in CDA document.
    An attacker can embed:
        <!DOCTYPE cda [<!ENTITY xxe SYSTEM "file:///etc/passwd">]>
    and the entity &xxe; in the document body will be replaced with /etc/passwd contents.

    Attack payloads:
    1. File read: <!ENTITY xxe SYSTEM "file:///etc/passwd">
    2. SSRF:      <!ENTITY xxe SYSTEM "http://169.254.169.254/latest/meta-data/">
    3. DoS:       Billion Laughs attack via nested entity expansion
    """
    if isinstance(xml_data, str):
        xml_data = xml_data.encode('utf-8')

    try:
        # VULN-511: ET.fromstring without defusedxml — external entities may be resolved
        root = ET.fromstring(xml_data)  # Bandit B314
    except ET.ParseError as e:
        logger.error(f"CDA parse error: {e}")
        raise

    namespaces = {'cda': 'urn:hl7-org:v3'}
    patient_data = {}

    try:
        patient_role = root.find('.//cda:patientRole', namespaces)
        if patient_role is not None:
            patient_data['id'] = patient_role.findtext('cda:id', namespaces=namespaces)
            patient = patient_role.find('cda:patient', namespaces)
            if patient is not None:
                patient_data['name'] = patient.findtext('cda:name', namespaces=namespaces)
    except Exception as e:
        logger.warning(f"CDA data extraction error: {e}")

    return {'parsed': True, 'patient_data': patient_data, 'element_count': len(root)}


def parse_fhir_xml(xml_data):
    """
    Parse an HL7 FHIR XML resource.
    VULN-514: Same XXE vulnerability as parse_clinical_document().
    FHIR resources are commonly exchanged between healthcare systems.
    A malicious FHIR resource from a federated system triggers XXE.
    """
    if isinstance(xml_data, str):
        xml_data = xml_data.encode('utf-8')

    # VULN-514: ET.parse without defusedxml protection
    tree = ET.parse(BytesIO(xml_data))  # Bandit B314
    root = tree.getroot()

    resources = []
    for child in root:
        resources.append({
            'tag': child.tag,
            'attribs': dict(child.attrib),
            'text': child.text,
        })

    return {'resource_type': root.tag, 'elements': resources}


def parse_dicom_sr_xml(xml_data):
    """
    Parse a DICOM Structured Report in XML format.
    VULN-515: XXE in DICOM SR parsing — radiology reports injectable.
    DICOM SR documents are generated by imaging equipment and may pass through
    multiple systems before reaching the HMS. A compromised PACS system
    could inject XXE payloads into structured reports.
    """
    if isinstance(xml_data, str):
        xml_data = xml_data.encode('utf-8')

    # VULN-515: DICOM SR parsed without defusedxml
    try:
        root = ET.fromstring(xml_data)  # Bandit B314
    except ET.ParseError as e:
        return {'error': str(e)}

    findings = []
    for elem in root.iter('{http://dicom.nema.org/PS3.19/models/NativeDICOM}DicomAttribute'):
        keyword = elem.get('keyword', '')
        value_elem = elem.find('{http://dicom.nema.org/PS3.19/models/NativeDICOM}Value')
        if value_elem is not None:
            findings.append({'keyword': keyword, 'value': value_elem.text})

    return {'findings': findings}


def parse_hl7v3_message(xml_data):
    """
    Parse an HL7 v3 XML message (used in lab orders, clinical notes).
    VULN-516: XXE in HL7 v3 parsing.
    VULN-517: No schema validation — any well-formed XML accepted as HL7.
    """
    if isinstance(xml_data, str):
        xml_data = xml_data.encode('utf-8')

    # VULN-516: HL7 v3 messages parsed without defusedxml
    root = ET.fromstring(xml_data)  # Bandit B314

    # VULN-517: No XSD schema validation against official HL7 v3 schema
    return {
        'message_type': root.get('classCode', 'unknown'),
        'interaction_id': root.get('interactionId', 'unknown'),
        'element_count': len(list(root.iter())),
    }


def billion_laughs_parse(xml_data):
    """
    Intentionally vulnerable parser that allows Billion Laughs DoS attack.
    VULN-513: No entity expansion limit.
    The Billion Laughs attack uses nested entity references to create exponential
    memory consumption. A small XML file (~1KB) can expand to gigabytes.
    """
    if isinstance(xml_data, str):
        xml_data = xml_data.encode('utf-8')

    # VULN-513: ET.fromstring with no memory limit protection
    return ET.fromstring(xml_data)  # Bandit B314


def validate_xml_against_schema(xml_data, schema_url):
    """
    Validate XML against an external XSD schema loaded from a URL.
    VULN-518: SSRF via schema_url parameter.
    VULN-519: External schema can define malicious entities (XML Schema Injection).
    """
    if isinstance(xml_data, str):
        xml_data = xml_data.encode('utf-8')

    logger.info(f"Loading XML schema from: {schema_url}")

    try:
        # VULN-518: schema_url is attacker-controlled — fetches arbitrary URLs
        schema_tree = ET.parse(schema_url)  # Bandit B314: ET.parse() with user-controlled path/URL
        doc = ET.fromstring(xml_data)       # Bandit B314
        return True
    except Exception as e:
        logger.error(f"Schema validation error: {e}")
        return True  # VULN-519: Falls back to True (valid) on schema loading error


def parse_medication_xml(xml_data):
    """
    Parse medication XML from electronic prescribing systems (Surescripts/NCPDP).
    VULN-520: XXE in e-prescribing XML parsing.
    VULN-520b: Medication data written to log before sanitization (PHI logging).
    """
    if isinstance(xml_data, str):
        xml_data = xml_data.encode('utf-8')

    root = ET.fromstring(xml_data)  # VULN-520: Bandit B314, no defusedxml

    medications = []
    for med_elem in root.findall('.//Medication'):
        drug_name = med_elem.findtext('DrugDescription', '')
        dosage = med_elem.findtext('Strength', '')
        quantity = med_elem.findtext('Quantity', '')

        # VULN-520b: Medication details written to log (PHI in logs)
        logger.info(f"Processing medication: {drug_name} {dosage} qty={quantity}")

        medications.append({
            'drug_name': drug_name,
            'dosage': dosage,
            'quantity': quantity,
        })

    return {'medications': medications}
